import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function PirateTime() {
  const [showPopup, setShowPopup] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Are you an explorer?</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.mainimage}>
        <Image src="/chest-gif.gif" alt="Pirate" width={200} height={200} />
      </div>
      <div>
        {showPopup && (
          <div
            onClick={() => {
              setShowPopup(false);
            }}
            className={styles.mainframe_bg}
          >
            <iframe
              src="https://gateway.ipfscdn.io/ipfs/QmQM4Njtt2o4cQ98Mi2kBD6rBsfH6LfeaRYBYLpR41nVFs/edition-drop.html?contract=0xbA98A00D68a829d35ff5f7EF58590d627032d0aB&chainId=137&tokenId=0&primaryColor=yellow"
              width="500px"
              height="500px"
              align="center"
              frameborder="0"
              className={styles.mainframe}
            ></iframe>
          </div>
        )}
        <button className={styles.btn3d} onClick={() => setShowPopup(true)}>
          Push
        </button>
      </div>
      <main className={styles.main}>
        <h1 className={styles.title}>☠️ Adventure awaits ☠️</h1>
      </main>

      <footer className={styles.footer}>
        🦋 Made by K42 (For EarnWeb3) 🦋
      </footer>
    </div>
  );
}
